config/routes.rb
Rails.application.routes.draw do

	root "articles#index"

	devise_for :utilisateurs, controllers: {
		registrations: 'utilisateurs/registrations'
	}

	resources :utilisateurs do
		collection do
			post :sign_in
		end
	end

	resources :articles do
		collection do
			get :mesarticles
		end
	end
end

app/models/article.rb
class Article < ApplicationRecord
	validates_presence_of :titre, :description, :prix
	belongs_to :utilisateur
	has_many :images
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.where(archive: false)
	end

	def mesarticles
		@articles = Article.where(utilisateur_id: current_utilisateur)
	end

	def show
		if utilisateur_signed_in?
			@article = Article.find(params[:id])
			if @article.archive and @article.utilisateur_id != current_utilisateur.id
				redirect_to(articles_path, alert: "Cette annonce est archivée et ne vous appartient pas")
			end
		else
			redirect_to(articles_path, alert: "Vous devez être connecté pour consulter les annonces")
		end
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(params.require(:article).permit(:titre, :prix, :description, :archive))
		@article.utilisateur = current_utilisateur
		if @article.save
			params[:article][:images].each do |i|
				@article.images.create file: i
			end
		end
		# params.require(:article)permit(:images).each do |i|
		# 	article.images.create file: i
		# end

		redirect_to @article
	end

	def edit
		@article = Article.find(params[:id])
		if utilisateur_signed_in?
			if current_utilisateur.id != @article.utilisateur_id
				redirect_to(articles_path, alert: "Vous n'êtes pas autorisé à modifier cet article")
			end
		else
			redirect_to(articles_path, alert: "Vous devez être connecté pour modifier un article")
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(params.require(:article).permit(:titre, :prix, :description, :archive, :utilisateur_id))
			redirect_to @article
		else
			render :edit
		end
	end

	def destroy
		@article = Article.find(params[:id])
		if utilisateur_signed_in?
			if current_utilisateur.id != @article.utilisateur_id
				redirect_to(articles_path, alert: "Vous n'êtes pas autorisé à supprimer cet article")
			else
				@article.images.each do |image|
					image.destroy
				end
				@article.destroy

				redirect_to articles_path
			end
		else
			redirect_to(articles_path, alert: "Vous devez être connecté pour supprimer un article")
		end
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.haml
%h1 Éditer l'annonce

= bootstrap_form_for(@article, multipart: true) do |f|
	%h3 Modification d'annonce
	.row
		.col-md-6.col-xs-12
			= f.text_field :titre, label: "Titre", placeholder: "Nom de l'article", content: @article.titre, required: true
			= f.number_field :prix, label: "Prix", content: @article.prix, required: true
			%label Images
			.input-group
				%span.input-group-btn
					%span.btn.btn-primary.btn-file
						Choisir un fichier
						= f.file_field :image, hide_label: true
				%input.form-control{:readonly => "readonly", :type => "text", :placeholder => "Images de l'article"}
			%br
		.col-md-6.col-xs-12
			= f.text_area :description, label: "Description", size: "60x6", placeholder: "Description de l'article", content: @article.description, required: true
		.col-md-6.col-xs-12
			- if @article.archive
				= f.check_box :archive, label: "Annonce archivée", checked: "checked"
			- else
				= f.check_box :archive, label: "Annonce archivée", checked: "unchecked"
	.row.text-center
		= f.submit "Modifier l'annonce", class: "btn btn-info"
%br
.row.text-center
	= button_to "Supprimer l'annonce", @article, class: "btn btn-danger", data: { confirm: "Êtes vous sûr de vouloir supprimer votre annonce ?\nCette action est irréversible..." }, method: :delete

app/views/articles/index.html.haml
%h1 Toutes les annonces
%p Il y a actuellement #{@articles.count} articles

- @articles.each do |article|
	.col-md-6.col-xs-12
		- if utilisateur_signed_in?
			%h2 #{link_to article.titre, article_path(article.id)} (#{article.prix} €)
		- else
			%h2 #{article.titre}
		- if article.images.first
			= image_tag article.images.first.file

app/views/articles/mesarticles.haml
%h1 Mes annonces

- @articles.each do |article|
	.col-md-6.col-xs-12
		%h2
			= link_to article.titre, article_path(article.id)
			- if article.archive
				(annonce archivée)
		- if article.images.first
			= image_tag article.images.first.file

app/views/articles/new.html.haml
%h1 Créer une annonce

- #{@article.utilisateur_id = Utilisateur.find_by_id(session[:current_user_id])}

= bootstrap_form_for(@article, multipart: true) do |f|
	%h3 Création d'annonce
	.row
		.col-md-6.col-xs-12
			= f.text_field :titre, label: "Titre", placeholder: "Nom de l'article", required: true
			= f.number_field :prix, label: "Prix", content: "0", required: true
			%label Images
			.input-group
				%span.input-group-btn
					%span.btn.btn-primary.btn-file
						Choisir un fichier
						= f.file_field :images, multiple: true, hide_label: true, required: true
				%input.form-control{:readonly => "readonly", :type => "text", :placeholder => "Images de l'article"}
			%br
		.col-md-6.col-xs-12
			= f.text_area :description, label: "Description", size: "60x6", placeholder: "Description de l'article", required: true
		.col-md-6.col-xs-12
			= f.check_box :archive, label: "Annonce archivée"
	.row.text-center
		= f.submit "Créer l'annonce", class: "btn btn-info"

app/views/articles/show.html.haml
- auteur = Utilisateur.find(@article.utilisateur_id)

%h1
	= @article.titre
	- if @article.archive == true
		(annonce archivée)
	- if auteur == current_utilisateur
		= link_to "Modifier l'annonce", edit_article_path, class: "btn btn-info"
%h3 Prix de l'article : #{@article.prix} €
%p= @article.description

%p
	- @article.images.each do |image|
		= image_tag image.file
		
%p Crée par l'utilisateur #{link_to auteur.prenom + " " + auteur.nom, utilisateur_path(@article.utilisateur_id)}