config/routes.rb
Rails.application.routes.draw do

	root "articles#index"

	devise_for :utilisateurs, controllers: {
		registrations: 'utilisateurs/registrations'
	}

	resources :utilisateurs do
		collection do
			post :sign_in
		end
	end

	resources :articles do
		collection do
			get :mesarticles
		end
	end
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
	.container-fluid
		.navbar-header
			=link_to "The Good Edge", root_path, class: "navbar-brand"
		.navbar-collapse.collapse
			=link_to "Toutes les annonces", articles_path, class: "navbar-brand"
			- if utilisateur_signed_in?
				=link_to "Mes annonces", mesarticles_articles_path, class: "navbar-brand"
				=link_to "Créer une annonce", new_article_path, class: "navbar-brand"
				.row.navbar_form.navbar-right.form-inline{style: "margin-top: 8px; margin-right: 5px;"}
					= link_to "Voir mon profil", utilisateur_path(current_utilisateur), class: "btn btn-default"
					= link_to "Modifier mes infos", edit_utilisateur_registration_path, class: "btn btn-default"
					= link_to "Se déconnecter", destroy_utilisateur_session_path, class: "btn btn-danger", method: :delete
			- else
				.row.navbar_form.navbar-right.form-inline{style: "margin-top: 8px; margin-right: 5px;"}
					= bootstrap_form_for(Utilisateur.new, url: sign_in_utilisateurs_path, multipart: true, html: {class: "navbar_form navbar-right form-inline"}) do |f|
						= f.email_field :email, placeholder: "Votre email", hide_label: true, required: true
						= f.password_field :password, placeholder: "Votre mot de passe", hide_label: true, required: true
						= f.submit "Connexion"
						= link_to "	Créer un compte", new_utilisateur_registration_path, class: "btn btn-info"

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title The Good Edge
		= csrf_meta_tags

		= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'
		= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css'
		= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'

		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

	%body
		= render "layouts/navbar"
		- if notice
			%p.alert.alert-success
				= notice
		- if alert
			%p.alert.alert-danger
				= alert
		.container
			= yield